apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: {{ .Release.Namespace }}
spec:
  cephVersion:
    image: ceph/ceph:v14.2.4-20190917
  dataDirHostPath: /var/lib/rook
  mon:
    count: {{ .Values.mon.count }}
    allowMultiplePerNode: true
  storage:
    useAllNodes: true
    useAllDevices: true
